name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: checkout common submodule
      run: git submodule update --init --remote
    - name: install dependencies
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y -qq install cmake ninja-build wget mingw-w64 bzip2 autoconf texinfo
    - name: build binutils
      run: bash ./.build-binutils.sh
    - name: build avr-gcc
      run: bash ./.build-avr-gcc.sh
    - name: check avr-gcc version
      run: avr-gcc --version
    - name: build avr-libc
      run: bash ./.build-avr-libc.sh
    - name: make test
      run: |
        cmake -S. -Bbuild -GNinja
        cmake --build build -v
